{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helmchartbuilder.serviceAccountName" . }}
  labels:
{{ include "helmchartbuilder.labels" . | nindent 4 }}
{{- end -}}
